### ISSUE TITLE
QR code does not work with hauts de seine

### ISSUE THREAD

**Issue by vingerha** [bain3/pronotepy#283] opened 2023-10-16 15:33 UTC
I believe this is a larger challenge seeing the history iwht 'regular' login but I wanted to add that also login via QR code runs into issues
```
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/pronote/config_flow.py", line 124, in async_step_qr_code_login
client = await self.hass.async_add_executor_job(get_client_from_qr_code, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/pronote/pronote_helper.py", line 51, in get_client_from_qr_code
client = (pronotepy.ParentClient if data['account_type'] == 'parent' else pronotepy.Client).qrcode_login(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pronotepy/clients.py", line 135, in qrcode_login
return cls(url, login, jeton, mode="qr_code", uuid=uuid)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pronotepy/clients.py", line 695, in __init__
super().__init__(pronote_url, username, password, ent, mode, uuid)
File "/usr/local/lib/python3.11/site-packages/pronotepy/clients.py", line 390, in __init__
super().__init__(pronote_url, username, password, ent, mode, uuid)
File "/usr/local/lib/python3.11/site-packages/pronotepy/clients.py", line 81, in __init__
self.attributes, self.func_options = self.communication.initialise()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pronotepy/pronoteAPI.py", line 76, in initialise
self.attributes = self._parse_html(get_response.content)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pronotepy/pronoteAPI.py", line 263, in _parse_html
raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.

**Comment by tarneaux** [comment] 2023-10-17 20:32
Hey, I'm not as familiar with this repo's codebase as its maintainers, but I'm guessing it will be hard for them to see what the root cause is exactly. This specific error being one of the most common if not *the* most common here, could you give us more information, like some steps to reproduce the error? It could also be useful which pronote instance you are trying to access.

**Comment by vingerha** [comment] 2023-10-18 06:48
HI, thanks for getitng back. I/we use the process as described in the documentation
1. logon to pronite uses https://enc.hauts-de-seine.fr/fr/ 
2. scan the QR code
3. use the code and pin and random uuid to access the client
4. if successful the client is you get a url, user and password which is then used to connect and generate a new pwd
5. any next connection uses the new pwd and generates a new pwd.

This works fine for multiple users across France and has helped to circumvent misisng/faulty ent/cas on pronotepy side.
Only this one seems to be a pita ... also for the conventional user/pwd/ent connection :) 
It is weird that it refers to the url where I would have expected this to not be needed.

The user having this issue is not me but am trying to help as I/we generated a add-on to pronotepy for to qrcode access
I also logged on to the mobile url and this seems to look the same as mine (in the 06/AM dept.)
The user having this issue shared the credentials with me and I can bring them in contact with you if you would like this too ..i.e. I will not forward them without permission as you understand.

**Comment by vingerha** [comment] 2023-10-18 06:52
Adding that wirh I/we is meant this HACS custom app: 
https://github.com/delphiki/hass-pronote

**Comment by bain3** [comment] 2023-11-18 20:19
Hi!
So does it not work at all, or can you log in at least once using the QR code directly?
Pronotepy still connects to the URL, but it shouldn't fail like this, since it is given to us by PRONOTE in the QR code json.

**Comment by bain3** [comment] 2023-11-18 20:44
Could you maybe share the QR code json? I'd like to see the URL it contains. You can censor the domain name.

**Comment by vingerha** [comment] 2023-11-19 08:46
Thanks and asked to the actual user for input, the credentials shared in October no longer work for me :)

**Comment by vingerha** [comment] 2023-11-19 09:05
And on the previous .. with OTHER schools it works fine...this one does not even connet the first time (error on top)

**Comment by ooii** [comment] 2023-11-19 09:18
Hi,

Here is the url in the json:
`"url":"https://0921162n.index-education.net/pronote/mobile.parent.html"`
Do you need more data from the json?

**Comment by bain3** [comment] 2023-11-19 13:52
Can you try it with the latest version?

```
pip install -U git+https://github.com/bain3/pronotepy
```

Your PRONOTE requires another special query parameter for some reason. Should be fixed in 0240969.

**Comment by ooii** [comment] 2023-11-19 19:56
It's working. Great job 🫡

**Closed** 2023-11-19 20:44 UTC

**Comment by ooii** [comment] 2023-11-21 15:53
Hi @bain3,
Do you have any ETA about the release of a version including this fix?

**Comment by ooii** [comment] 2023-12-05 18:02
@bain3 me again trying to figure out when you think you'll release a news version of your library please. The last one is 3 months old and several issues have been fixed since then.
Thanks a lot.

**Comment by bain3** [comment] 2023-12-05 18:43
Hi, sorry. Totally forgot about it. Should be out in a moment.
