### ISSUE TITLE
Probleme de connection

### ISSUE THREAD

**Issue by Erusel** [bain3/pronotepy#117] opened 2022-03-15 17:36 UTC
Une idée de pourquoi j'ai cette erreur ? :

  File "C:/Users/***/Desktop/pytest/main.py", line 5, in <module>
    client = pronotepy.Client('https://lyc-monge.ac-grenoble.fr/pronote/eleve.html',
  File "C:\Users\***i\AppData\Local\Programs\Python\Python38\lib\site-packages\pronotepy\clients.py", line 283, in __init__
    super().__init__(pronote_url, username, password, ent)
  File "C:\Users\***i\AppData\Local\Programs\Python\Python38\lib\site-packages\pronotepy\clients.py", line 50, in __init__
    cookies = ent(username, password)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\pronotepy\ent.py", line 79, in ac_grenoble
    return educonnect(response.url, cookies, username, password)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\pronotepy\ent.py", line 31, in educonnect
    "RelayState": soup.find("input", {"name": "RelayState"})["value"],
TypeError: 'NoneType' object is not subscriptable

**Comment by Bapt5** [comment] 2022-03-15 19:10
Si tu utilises un compte educonnect met la fonction `ent_auvergnerhonealpe` et sinon je crois que pour Grenoble il n'y a pas encore de compte educonnect donc utilises la fonction `ac_grenoble`

**Comment by Bapt5** [comment] 2022-03-15 22:03
@Erusel Pouvez-vous m'envoyer le programme que vous exécutez svp ?

**Comment by Bapt5** [comment] 2022-03-16 15:31
Yes but It can be also a login issue if @Erusel don't use the `client.logged_in` condition. That's why I want to see the code 😅

**Comment by Bapt5** [comment] 2022-03-23 08:56
I'm trying to implement #41 and I have this error. I think the messages system is broken. I will try to rework it. So, your error is not a login error, it is just caused by using the method `client.messages()` . @bain3 I think we can close this issue.

**Comment by bain3** [comment] 2022-03-23 21:31
Yes, this is no longer a login issue.

**Closed by bain3** 2022-03-23 21:31 UTC
