### ISSUE TITLE
Unable to connect to my Pronote using Pronotepy 2.1.0 (latest)

### ISSUE THREAD

**Issue by DodoLeDev** [bain3/pronotepy#63] opened 2021-10-05 18:21 UTC
Every time I am trying to connect to my Pronote, the console always returns me the same debug info, but never success to connect :
```py
DEBUG:pronotepy.pronoteAPI:Requesing html: https://0342066l.index-education.net/pronote/eleve.html?login=true
DEBUG:pronotepy.pronoteAPI:[_Communication.post] decryption change
INFO:pronotepy.pronoteAPI:Have you tried turning it off and on again? ERROR: 25 |
DEBUG:pronotepy.pronoteAPI:Requesing html: https://0342066l.index-education.net/pronote/eleve.html?login=true
DEBUG:pronotepy.pronoteAPI:[_Communication.post] decryption change
INFO:pronotepy.pronoteAPI:Have you tried turning it off and on again? ERROR: 25 |

...etc...
```
How can I resolve this issue?

***P.-S.** : After trying to resolve myself this issue, the Pronote portal blocks my IP for too many incorrect credentials entered!* 😅

**Comment by bain3** [comment] 2021-10-05 19:04
Hello,
looks like your login credentials are incorrect... At least from what I can see error 25 is this:
![image](https://user-images.githubusercontent.com/31798786/136085994-635c62c3-e1af-4e14-8fa2-991583c5bca1.png)
Although rapidly reconnecting like this isn't intended, I'll fix it.

**Comment by bain3** [comment] 2021-10-10 10:26
Hello, I am closing this issue for now. The re-connection bug was fixed, right now you probably just have the wrong credentials or need to use your ENT.

**Closed by bain3** 2021-10-10 10:26 UTC
Labels: bug

**Comment by DodoLeDev** [comment] 2021-10-10 10:54
_(@bain3 Is it possible to reopen this issue? 🙏🙄 )_

**Comment by bain3** [comment] 2021-10-10 11:50
This is expected behaviour when your credentials are incorrect :) Do you normally use an ENT when you connect to pronote?

**Comment by DodoLeDev** [comment] 2021-10-10 16:55
I can, but it's not needed...
And the link I provided doesn't need to use any ENT portal...

The credentials are correct, I have tested them!
